name: Test Repo
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
        with:
          repository: hemanthx13/second-action-react-demo
      - name: Folder-Structure
        run: |
          ls -al
          echo 'work dir'
          pwd                    

      - name: install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: |
          npm ci
          npm test
