name: Hello World

on:
  push:
    branches: [ test33 ]
  workflow_dispatch:
    inputs:
      name:
        description: 'Who are you saying hello to?'
        required: false
        default: 'World'

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, $ { { github.event.inputs.name || 'World' }}!
