name: Hello World

on:
  push:
    branches: [ feature33 ]
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, $ { { github.event.inputs.name || 'World' }}!
